### PR TITLE
PWA report

### PR DESCRIPTION
**Pull request by tomayac**
This is the current state:

localhost_8080_reports_progressive-web-apps 2

### CODE REVIEW

**Comment by rviscomi** [comment]
Thanks for getting this together, it looks like a ton of effort. Some suggestions:

- `response_bodies.*` is EXTREMELY expensive to query and we will incur that cost every two weeks. I think we need to take a similar approach to the `technologies` dataset, where we do a one-time backfill of all of the old tables going back to 2016_01_01 and incrementally append new tables to the dataset each biweekly crawl.

- There are helper queries generating the tables in the `scratchspace` dataset. This is a job better suited for Dataflow, which gets the BQ data in a stable place for us to then generate high-level reports.

- Are there any opportunities to offload some of these detections even more upstream, for example in Wappalyzer or WebPageTest or even Chrome? cc @pmeenan 

- `scratchspace` is more like a /tmp directory so we shouldn't dump critical data there. This seems like a good fit for the `technologies` dataset, which describes tech used on pages and is already broken down into YYYY_MM_DD tables. For any URLs that are detected to be PWAs, we can append them to the table with category/app indicating that it's a PWA and the `info` field can contain any metadata needed by the metrics. Since there's a lot of metadata maybe it should even be JSON serialized.

- We don't need to preprocess the Lighthouse results. Each metric can query the `lighthouse` dataset directly. Eg [see the hreflang query](https://github.com/HTTPArchive/bigquery/blob/master/sql/timeseries/hreflang.sql). Same for the use counters, just query the `pages` dataset directly.

- Rather than querying for unused p10..p90 values, select only the data you need. Eg, percent of pages with X aliased `percent`. [See my related comment in the other PR](https://github.com/HTTPArchive/httparchive.org/pull/51/files#r204508601) and the hreflang example above.

**Comment by pmeenan** [comment]
What needs to be pulled from the bodies?  There are 3 good sources for a lot of this kind of content that are probably much cheaper to pull (in the pages-level data) and I'd much rather see the detections pushed upstream where possible.

1 - Wappalyzer: Things like workbox make total sense to add the the javascript library detection.

2 - Lighthouse: Most of the PWA features should be detected by the lighthouse PWA checks and those that aren't should maybe be added.

3 - Chrome feature usage histograms.  Chrome reports back to UMA when specific features are used on a page (CSS or platform features).  Those features are also pulled out by WPT and reported.  If they aren't already, it may make sense to instrument the different SW event listeners.

**Comment by tomayac** [comment]
I have addressed some of the points already, please see https://github.com/HTTPArchive/httparchive.org/pull/51#issuecomment-407437170.

For the Wappalyzer bit, I am seeing if I can create, then land, a Pull Request that would add Workbox detection.

**Comment by tomayac** [comment]
I'm closing this and break it down into small, iterative Pull Requests.

**Pull request closed without merging**
