### PR TITLE
Reimplement HAR data pipeline with Apache Beam in Python

### PR DESCRIPTION
**Pull request by rviscomi**
This replaces the obsolete Java Dataflow SDK, which hasn't worked since October 2020. The implementation uses the latest Apache Beam Python SDK, version 2.26.0. It introduces new dependencies to the pipeline, so the GCE worker responsible for executing `sync_har.sh` must also follow the installation instructions in the README, including a secret `credentials/auth.json` file with service account credentials to run the Dataflow jobs.

I did also try to use `ujson` instead of `json` for possible performance gains, but ran into dependency issues on Dataflow. The pipeline runs without it, albeit slowly, so this is something we can defer for future optimizations.

Fixes https://github.com/HTTPArchive/httparchive.org/issues/232

### CODE REVIEW

**Comment by rviscomi** [comment]
I've successfully started a Dataflow job on the GCE worker by running `./sync_har.sh android 2020-12-01` after checking out this branch and going through the setup steps.

image


It will probably take 14 hours to complete, so if it works I'll merge this PR and rerun it again on the 2020_11_01_mobile dataset, which is still missing the Lighthouse table. After that we should be caught up and in good shape to process the January crawl at the end of the month.

The only remaining thing is I have a nagging feeling about possible permissions issues arising from setting everything up as `root` but the pipeline running each month as `igrigorik`.

**Comment by rviscomi** [comment]
The November desktop crawl completed successfully.

**Comment by infosec-au** [comment]
Thank you so much @rviscomi for your work on this. I'm excited to use the new data.

**Comment by rviscomi** [comment]
Glad this was able to unblock you @infosec-au and thanks for your donation!

**Pull request merged**
